name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 23.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install sops
      run: |
        # Install sops
        curl -L https://github.com/mozilla/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64 -o sops
        chmod +x sops
        sudo mv sops /usr/local/bin/
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    
    - name: Decrypt secrets
      run: |
        export SOPS_AGE_KEY=${{ secrets.SOPS_AGE_KEY }}
        sops -d secrets/secrets.yaml > .secrets.yaml
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      if: always()