name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install sops
        run: |
          # Install sops
          curl -L https://github.com/mozilla/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64 -o sops
          chmod +x sops
          sudo mv sops /usr/local/bin/
      
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      
      - name: Decrypt secrets
        run: |
          export SOPS_AGE_KEY=${{ secrets.SOPS_AGE_KEY }}
          sops -d secrets/secrets.yaml > .secrets.yaml
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm ci
      
      - uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extensions: 'js,jsx,ts,tsx'
          annotations: true